### ISSUE TITLE
Changes to implement a SupportProfile importing scheme

### ISSUE THREAD

**Issue by PiezPiedPy** [MoreRobustThanYou/Kerbalism#2]
# Changes to implement a SupportProfile importing scheme

Originally proposed in an issue for the original Kerbalism here: https://github.com/ShotgunNinja/Kerbalism/issues/111

I needed a way to import processes for my personal changes and came up with some small code changes that enable Profiles that are stored in any config file to be imported into the loaded profile, this also allows modders to include their own Supplies, Rules or Processes and not have to edit the default profile.

The code checks a field supplied in the support profile to determine if the mod the profile is for exists. This mechanism works by searching the GameData directory for a matching directory that is named in the `moddir` field of the support profile.
# 
### Using
Simply create a Profile node named KerbalismSupport and include the necessary script to define the Supplies, Rules and Processes you need, as you would with the default profile.
The KerbalismSupport profile node must have a `modname` field which is used for logging and a `moddir` field which is used to decide whether or not a mods support profile should be loaded based on the existence of the mod's directory.
```
Profile
{
	name = KerbalismSupport    // name must be KerbalismSupport
	modname = FooBar Zoo       // Just a name for display purposes
	moddir = FooBar/Zoo        // Could use Zoo if you wish

	Supply
	{
    etc...
```
#### Example:  [FooBarZoo.cfg](https://github.com/PiezPiedPy/Kerbalism-Original/blob/cbb5fdbeb08989e0f38410228bb59d172f7b125e/GameData/Kerbalism/Support/FooBarZoo.cfg)

see the commits here:
* [Profile-Import-Test branch](https://github.com/PiezPiedPy/Kerbalism-Original/commits/Profile-Import-Test)
* [commit](https://github.com/PiezPiedPy/Kerbalism-Original/commit/1aa431b47b05fa3d0cbf244904ad45aea675a8d7)

If you have any suggestions fire away, code is ready for a Pull 😉 

If this proposed change is accepted, it will allow me to add the support changes necessary to make the mods USI, MKS and FTT able to integrate with Kerbalism without source code changes.
* In essence all MKS resources will be replaced with Kerbalisms.
* Integration of Kerbalisms chemical processes will be imported into the parts etc.
* A SupportProfile will allow new processes that for example enable the Nuclear Reactors of FTT and their nuclear fuels to be processed.
* I have done the majority of the work and the mods are working nicely with Kerbalism on my private build 😎

**Comment by MoreRobustThanYou** [comment]
@PiezPiedPy Did you find a way to make MKS's bonuses work?

**Comment by PiezPiedPy** [comment]
> Did you find a way to make MKS's bonuses work?

Not got that far into it and doubt I will try to use any of the MKS systems but that may change depending on any spare time I have to mess with such things.

The USI and FTT mods are installed as usual but for MKS all I have done so far is just install the parts from it. I have basically just removed their modules via MM and added Kerbalisms modules, resources and processes where needed.

Processes for e.g. the USI Nuclear reactors and any resources needed I used a SupportProfile to import them into Kerbalism, such as a Reactor process and other processes for the needed fuel supplies i.e. a Uranium centrifuge, Hydrogen liquefaction etc.

**So far I have these processes for USI/FTT.**
* Uraninite Centrifuge to extract Enriched Uranium from Uraninite ore.
* Depleted Fuel - Breeder Reactor to extract Enriched Uranium from Depleted Fuel.
* Hydrogen Liquefaction for creating LqdHydrogen from Hydrogen gas.
* Nuclear Reactor for the reactors.

**Kerbalism support for USI/FTT consists of:**
* Processes as above.
* Added Uraninite mining, storage and processing, larger nuclear tanks and radiation emitters for the nuclear parts.
* Removed Warehouse, Recycle, Logistics, Power, Weight Distribution Modules etc.
* Placed FTT Parts into suitable Tech Tree locations.


**Kerbalism support for USI Kontainers consists of:**
* Removed resources not used by Kerbalism from Kontainers and added Kerbalism resources.
* Removed Warehouse, Recycle and Weight Distribution Modules etc from all Kontainers,
* Placed Kontainers into suitable Tech Tree locations.

I was at first planning on making a separate mod to hold the .cfg files but they could be included in Kerbalisms/Support folder.

**Comment by MoreRobustThanYou** [comment]
Can you test my branch and ensure _**everything**_ works?

**Comment by PiezPiedPy** [comment]
I've just finished checking on my own development branch which is identical to your branch and all worked OK.
